# Generated by Django 3.0.6 on 2020-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '博客表', 'verbose_name_plural': '博客表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='commit',
            options={'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签表', 'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='upanddown',
            options={'verbose_name': '点赞点踩表', 'verbose_name_plural': '点赞点踩表'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
