# Generated by Django 3.0.6 on 2020-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200525_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default='摘要', max_length=255, verbose_name='文章摘要'),
        ),
        migrations.AddField(
            model_name='article',
            name='down_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='up_num',
            field=models.IntegerField(default=0),
        ),
    ]
